### ISSUE TITLE
Deployment section

### ISSUE THREAD

**Issue by btcdrak** [jgarzik/bip100#6]
Can I suggest you add a "deployment" section in the BIP and move points 5 & 6 there. This is more in line with how BIPs have been written in the past. 

(Ideally it would be better also to have the deployment section left at TBD).

**Comment by jgarzik** [comment]
done

I would prefer to leave it in -- but you are welcome to request a BIP link/reference...

**Comment by btcdrak** [comment]
OT: Is there any reason this isnt a fork of the bips repository so a pull request can be made?

**Comment by jgarzik** [comment]
@btcdrak  You can make a pull req here.  It's just easier this way while the spec is changing frequently.  Once it settles down, it will become a bip.git pull request as noted on bitcoin-dev m-l.

**Comment by btcdrak** [comment]
Sure, but you're making things more complex than they need to be. Pull requests/issues can be made against a bips fork too, and often are.
